### ISSUE TITLE
Add GitHub Authentication

### ISSUE THREAD

**Issue by brunoao86** [brunoao86/rails-third-party-auth#5]
I will tell you what to do and add code references, since the architecture is not documented yet. =(

- Configure GitHub to callback [our route](https://github.com/brunoao86/rails-third-party-auth/blob/master/config/routes.rb#L2) and get the GitHub keys

- Add the GitHub keys on `config/local_env`

- Add gem [omniauth-github](https://github.com/intridea/omniauth-github) on the project

- Configure `config/initializers/omniauth.rb` to work with GitHub, fetching the keys from ENV

- Create the `RequestGithub`, like [RequestGoogle](https://github.com/brunoao86/rails-third-party-auth/blob/master/app/services/user_authentication_service/request_google.rb) and [RequestFacebook](https://github.com/brunoao86/rails-third-party-auth/blob/master/app/services/user_authentication_service/request_facebook.rb)

- Adjust [RequestProviderBuilder](https://github.com/brunoao86/rails-third-party-auth/blob/master/app/services/user_authentication_service/request_provider_builder.rb) to work with the new authentication

- Finally, add the GitHub button on [login page](https://github.com/brunoao86/rails-third-party-auth/blob/master/app/views/sessions/new.html.erb)

And that's it! 😎

**Comment by m3nd3s** [comment]
I'm working on it 😎

**Comment by brunoao86** [comment]
@m3nd3s, I've updated the issue description adding one more item:

*Add gem omniauth-github on the project*

**Comment by brunoao86** [comment]
Deployed! ❤️ 

https://rails-third-party-auth.herokuapp.com/login
