### ISSUE TITLE
Add LinkedIn Authentication

### ISSUE THREAD

**Issue by brunoao86** [brunoao86/rails-third-party-auth#6]
I will tell you what to do and add code references, since the architecture is not documented yet. =(

- Configure LinkedIn to callback [our route](https://github.com/brunoao86/rails-third-party-auth/blob/master/config/routes.rb#L2) and get the LinkedIn keys

- Add the LinkedIn keys on `config/local_env`

- Add gem [omniauth-linkedin](https://github.com/skorks/omniauth-linkedin) on the project

- Configure `config/initializers/omniauth.rb` to work with LinkedIn, fetching the keys from ENV

- Create the `RequestLinkedin`, like [RequestGoogle](https://github.com/brunoao86/rails-third-party-auth/blob/master/app/services/user_authentication_service/request_google.rb) and [RequestFacebook](https://github.com/brunoao86/rails-third-party-auth/blob/master/app/services/user_authentication_service/request_facebook.rb)

- Adjust [RequestProviderBuilder](https://github.com/brunoao86/rails-third-party-auth/blob/master/app/services/user_authentication_service/request_provider_builder.rb) to work with the new authentication

- Finally, add the LinkedIn button on [login page](https://github.com/brunoao86/rails-third-party-auth/blob/master/app/views/sessions/new.html.erb)

And that's it! 😎

**Comment by koushic88** [comment]
I can take this.

**Comment by koushic88** [comment]
I looked at LinkedIn docs, looks like their api don't return 'Gender' data field.

**Comment by brunoao86** [comment]
Hi, @koushic88! Thank you for spending some time on it!

About the `Gender`, relax, let's ignore this data field for now.

**Comment by brunoao86** [comment]
I had to make another request to get `gender` and `locale` on `RequestFacebook` 😞 

https://github.com/brunoao86/rails-third-party-auth/blob/master/app/services/user_authentication_service/request_facebook.rb#L59-L66

**Comment by vedipen** [comment]
I would like to contribute to this, if its fine. @koushic88

**Comment by vedipen** [comment]
I would like to contribute to this, if its fine. @brunoao86

**Comment by brunoao86** [comment]
Be my guest, @vedipen! ✌️ 

I think that @koushic88 is not working on this anymore. 😞

**Comment by brunoao86** [comment]
Deployed! ❤️ 

https://rails-third-party-auth.herokuapp.com/login
