### ISSUE TITLE
Add Twitter Authentication

### ISSUE THREAD

**Issue by brunoao86** [brunoao86/rails-third-party-auth#7]
I will tell you what to do and add code references, since the architecture is not documented yet. =(

- Configure Twitter to callback [our route](https://github.com/brunoao86/rails-third-party-auth/blob/master/config/routes.rb#L2) and get the Twitter keys

- Add the Twitter keys on `config/local_env`

- Add gem [omniauth-twitter](https://github.com/arunagw/omniauth-twitter) on the project

- Configure `config/initializers/omniauth.rb` to work with Twitter, fetching the keys from ENV

- Create the `RequestTwitter`, like [RequestGoogle](https://github.com/brunoao86/rails-third-party-auth/blob/master/app/services/user_authentication_service/request_google.rb) and [RequestFacebook](https://github.com/brunoao86/rails-third-party-auth/blob/master/app/services/user_authentication_service/request_facebook.rb)

- Adjust [RequestProviderBuilder](https://github.com/brunoao86/rails-third-party-auth/blob/master/app/services/user_authentication_service/request_provider_builder.rb) to work with the new authentication

- Finally, add the Twitter button on [login page](https://github.com/brunoao86/rails-third-party-auth/blob/master/app/views/sessions/new.html.erb)

And that's it! 😎

**Comment by jb-1980** [comment]
I would like to work on this.

**Comment by brunoao86** [comment]
Nice, @jb-1980! Feel free to contribute!

Sorry, but I forgot to mention above the gem that must be added on the project to make it work: https://github.com/arunagw/omniauth-twitter

**Comment by jb-1980** [comment]
Thanks! I just found that as I was trying to run.
